services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"       
    develop:
      watch:
        - action: sync
          path: ./frontend/src
          target: /app/src
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app

